package com.apurva.onboarding.extraction;

import jakarta.annotation.PreDestroy;
import org.springframework.stereotype.Component;
import tools.jackson.databind.ObjectMapper;
import java.nio.file.Files;
import java.sql.*;
import java.time.Instant;
import java.util.*;

/** Embedded H2 takes a process lock. One durable store owns both canonical IDs and Sheet rows. */
@Component
public class ExtractionStore {
    private final Connection db;
    private final ObjectMapper json = new ObjectMapper();
    public ExtractionStore(ExtractionSettings settings) throws Exception {
        Files.createDirectories(settings.dataDir);
        db = DriverManager.getConnection("jdbc:h2:file:" + settings.dataDir.toAbsolutePath().resolve("reviews")
                + ";DB_CLOSE_ON_EXIT=FALSE;WRITE_DELAY=0", "sa", "");
        try (Statement s = db.createStatement()) {
            s.execute("CREATE TABLE IF NOT EXISTS documents (id VARCHAR PRIMARY KEY, hash VARCHAR UNIQUE NOT NULL, result CLOB, sheet_row BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 2), synced BOOLEAN DEFAULT FALSE)");
            s.execute("CREATE TABLE IF NOT EXISTS aliases (alias VARCHAR PRIMARY KEY, id VARCHAR NOT NULL REFERENCES documents(id))");
            s.execute("CREATE TABLE IF NOT EXISTS audit (seq BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, id VARCHAR NOT NULL, event CLOB NOT NULL)");
            s.execute("CREATE TABLE IF NOT EXISTS settings (name VARCHAR PRIMARY KEY, val VARCHAR NOT NULL)");
        }
    }
    public synchronized String reserve(String requestedId, String hash) throws SQLException {
        db.setAutoCommit(false);
        try {
            String existing = scalar("SELECT d.hash FROM aliases a JOIN documents d ON a.id=d.id WHERE a.alias=?", requestedId);
            if (existing != null && !existing.equals(hash)) throw new IdConflict();
            String id = scalar("SELECT id FROM documents WHERE hash=?", hash);
            if (id == null) {
                id = requestedId;
                execute("INSERT INTO documents(id,hash) VALUES (?,?)", id, hash);
            }
            if (existing == null) execute("INSERT INTO aliases(alias,id) VALUES (?,?)", requestedId, id);
            db.commit();
            return id;
        } catch (SQLException | RuntimeException e) { db.rollback(); throw e; }
        finally { db.setAutoCommit(true); }
    }
    public synchronized ExtractionResult get(String id) throws SQLException {
        String value = scalar("SELECT result FROM documents WHERE id=COALESCE((SELECT id FROM aliases WHERE alias=?),?)", id, id);
        return value == null ? null : json.readValue(value, ExtractionResult.class);
    }
    public synchronized void save(ExtractionResult result) throws SQLException {
        db.setAutoCommit(false);
        try {
            execute("UPDATE documents SET result=?,synced=FALSE WHERE id=?", json.writeValueAsString(result), result.submissionId());
            audit(result.submissionId(), Map.of("stage", "FINAL", "timestamp", Instant.now().toString(), "inputHash", result.inputHash(), "result", result));
            db.commit();
        } catch (SQLException | RuntimeException e) { db.rollback(); throw e; }
        finally { db.setAutoCommit(true); }
    }
    public synchronized void audit(String id, Map<String, ?> event) throws SQLException {
        execute("INSERT INTO audit(id,event) VALUES (?,?)", id, json.writeValueAsString(event));
    }
    public synchronized List<Object> audit(String id) throws SQLException {
        return rows("SELECT event FROM audit WHERE id=COALESCE((SELECT id FROM aliases WHERE alias=?),?) ORDER BY seq", id, id)
                .stream().map(v -> (Object) json.readTree(v)).toList();
    }
    public synchronized List<ExtractionResult> reviews() throws SQLException {
        return rows("SELECT result FROM documents WHERE result IS NOT NULL ORDER BY sheet_row")
                .stream().map(v -> json.readValue(v, ExtractionResult.class)).filter(r -> !r.reviewQueue().isEmpty()).toList();
    }
    public synchronized List<ExtractionResult> pending() throws SQLException {
        return rows("SELECT result FROM documents WHERE result IS NOT NULL AND synced=FALSE ORDER BY sheet_row")
                .stream().map(v -> json.readValue(v, ExtractionResult.class)).toList();
    }
    public synchronized long row(String id) throws SQLException { return Long.parseLong(scalar("SELECT sheet_row FROM documents WHERE id=?", id)); }
    public synchronized void markSynced(ExtractionResult snapshot) throws SQLException {
        // A concurrent re-extraction must not be marked synced by an older in-flight write.
        execute("UPDATE documents SET synced=TRUE WHERE id=? AND result=?", snapshot.submissionId(), json.writeValueAsString(snapshot));
    }
    public synchronized void bindSheet(String target) throws SQLException {
        String bound = scalar("SELECT val FROM settings WHERE name='sheet'");
        if (bound != null && !bound.equals(target)) throw new IllegalStateException("Store is already bound to a different Sheet");
        if (bound == null) execute("INSERT INTO settings(name,val) VALUES ('sheet',?)", target);
    }
    private void execute(String sql, String... args) throws SQLException {
        try (PreparedStatement s = db.prepareStatement(sql)) { bind(s, args); s.executeUpdate(); }
    }
    private String scalar(String sql, String... args) throws SQLException { var r = rows(sql, args); return r.isEmpty() ? null : r.getFirst(); }
    private List<String> rows(String sql, String... args) throws SQLException {
        List<String> values = new ArrayList<>();
        try (PreparedStatement s = db.prepareStatement(sql)) {
            bind(s, args);
            try (ResultSet r = s.executeQuery()) { while (r.next()) values.add(r.getString(1)); }
        }
        return values;
    }
    private void bind(PreparedStatement s, String[] args) throws SQLException { for (int i=0;i<args.length;i++) s.setString(i+1,args[i]); }
    @PreDestroy public synchronized void close() throws SQLException { db.close(); }
    public static class IdConflict extends RuntimeException {}
}
